#+AUTHOR: Johannes Rainer
#+EMAIL: johannes.rainer@eurac.edu
#+DATE: December, 2017
#+SETUPFILE: orgsetup.org

* Enabling analysis of large scale metabolomics/proteomics data: /on-the-fly/ data access in =MSnbase=

*EuroBioc2017*, December 2017, Cambridge.

+ Updates to =mzR=, =MSnbase= and =xcms= packages:
  - /on-the-fly/ data access.
  - Mass spectrometry (MS) data write support.
  - towards a common MS infrastructure: =xcms= re-uses classes from
    =MSnbase=.

** =onDisk= /vs/ =inMem= data mode; why?

+ Keeping all data in memory prevents analysis of large experiments.
+ _Example_: load a MS file
  #+BEGIN_SRC R
    library(MSnbase)
    library(pryr)

    ## Read a single MS level 1 file
    msd <- readMSData("data/150616_POOL_IntraP_S_POS_6.mzML", mode = "onDisk")

    ## Object size?
    object_size(msd)

    ## retention time per spectrum
    head(rtime(msd))

  #+END_SRC
+ Memory footprint: 977 MB (=inMem=) /vs/ 600 kB (=onDisk=).
+ Reading data on demand: /relatively/ fast for indexed mzML files.

** Application example: /centroiding/ of /profile/ MS data

+ Profile MS data?
  _Example_: plot MS data for a metabolite:
  #+BEGIN_SRC R
    library(xcms)
    library(magrittr)

    ## m/z for Taurine [M+H]+
    taur_mz <- 126.02194
    taur_rt <- c(169, 176)

    ## Extract the MS data for this ion
    taur_msd <- msd %>%
        filterRt(rt = taur_rt) %>%
        filterMz(mz = c(taur_mz - 0.01, taur_mz + 0.01)) %>%
        extractMsData

    plotMsData(taur_msd[[1]])

  #+END_SRC

+ /centroiding/: represent mass peaks by their /centroid/ (largest signal per mass
  peak).

+ centroiding =onDisk= data: lazy execution of data manipulations.
  _Example:_ Data smoothing (=smooth=) and centroiding (=pickPeaks=).
  #+BEGIN_SRC R
    ## 1) smooth the spectrum data
    ## 2) perform centroiding
    cntr <- msd %>%
        smooth(method = "MovingAverage", halfWindowSize = 2L) %>%
        pickPeaks()

    ## ... not executed yet ...
    cntr@spectraProcessingQueue

    ## Extract the MS data for our example ion;
    ## smoothing and centroiding performed on-the-fly
    taur_cntr <- extractMsData(cntr, rt = taur_rt,
                               mz = c(taur_mz - 0.01, taur_mz + 0.01))

    plotMsData(taur_cntr[[1]])
  #+END_SRC

+ /Make persistent/: write to MS data file.
  _Example_: write the centroided data to disk.
  #+BEGIN_SRC R
    writeMSData(cntr, file = "centroided.mzML", copy = TRUE)

    ## 1) All processings (smoothing and peak picking) are applied
    ## 2) Data is exported as mzML
  #+END_SRC

** Finally

*Thank you for your attention!*

Collaborative work:
- Laurent Gatto (CPU Cambridge, UK)
- Sebastian Gibb (University Medicine Greifswald, Germany)
- Johannes Rainer (Eurac Research, Italy)
- Steffen Neumann (IPB Halle, Germany)


clone me! https://github.com/jotsetung/EuroBioc2017-MSnbase.git

